% MAKE_SWEEPS generates and saves sweep figures
    % 
    % Generates and saves figures generated by the kpolysweep function and 
    % the ltplot function of the lookuptable in options.
    % Must specify an options object to be used -- this object should specify
    % where the figures will be saved as well as the appropriate lookuptable.
    %
    % See also KPOLYSWEEP, FORMIN, MAKE_EXPERIMENT_OBJS, OPTIONS, LOOKUPTABLE/LTPLOT.

%% Set variables
opts=opts;

bestfits={fit_3st,fit_4st,fit_4st_krel};

%% Make and save kpoly sweep figures
set(groot,'defaultfigureposition',[400 250 900 750]) % helps prevent cut offs in figs
for i=1:length(bestfits)
    opts.applytable(bestfits{i})
    opts.update_results_folder
    opts.resultsfolder=strcat(opts.resultsfolder," ",opts.kpoly_type,num2str(i));
    kpolysweep(opts,"PRM size","log2",true)
    kpolysweep(opts,"FH1 length","log2",true)
    kpolysweep(opts,"FH2 dist","log2",true)
    kpolysweep(opts,"NT dist","log2",true)
    kpolysweep(opts,"k_cap","log2",true)
    kpolysweep(opts,"k_del","log2",true)
    kpolysweep(opts,"r_cap","log2",true)
    kpolysweep(opts,"r_cap_exp","log2",true)
    if opts.kpoly_type~="3st"
        kpolysweep(opts,"r_del","log2",true)
        kpolysweep(opts,"k_rel","log2",true)
    end
end

%% Make and save polymerstat sweep figures
opts.update_results_folder
skip=20;
opts.resultsfolder=strcat(opts.resultsfolder," polymerstat sweep");
fig=opts.lookup.ltplot("NTdist","Prvec0",skip,type="ratio",ratioscale="log2");
xlim([100 600])
figuresave(fig,opts,strcat("inset Sweep_Change in Prvec0 vs. distance to NT_skip",num2str(skip),".fig"),true);
ylim([-20 1])
xlim([0 600])
figuresave(fig,opts,strcat("Sweep_Change in Prvec0 vs. distance to NT_skip",num2str(skip),".fig"),true);

fig=opts.lookup.ltplot("length","Prvec0",skip,type="ratio",ratioscale="log2");
xlim([300 600])
figuresave(fig,opts,strcat("inset Sweep_Change in Prvec0 vs. FH1 length_skip",num2str(skip),".fig"),true);
ylim([-20 1])
xlim([0 600])
figuresave(fig,opts,strcat("Sweep_Change in Prvec0 vs. FH1 length_skip",num2str(skip),".fig"),true);

fig=opts.lookup.ltplot("CTdist","Prvec0",skip,type="ratio",ratioscale="log2");
xlim([300 600])
figuresave(fig,opts,strcat("inset Sweep_Change in Prvec0 vs. distance to FH2_skip",num2str(skip),".fig"),true);
ylim([-20 1])
xlim([0 600])
figuresave(fig,opts,strcat("Sweep_Change in Prvec0 vs. distance to FH2_skip",num2str(skip),".fig"),true);

skip=5;
fig=opts.lookup.ltplot("NTdist","POcclude",skip,type="ratio",ratioscale="log2");
xlim([50 600])
figuresave(fig,opts,strcat("inset Sweep_Change in POcclude vs. distance to NT_skip",num2str(skip),".fig"),true);
xlim([0 600])
ylim([-11 0.5])
figuresave(fig,opts,strcat("Sweep_Change in POcclude vs. distance to NT_skip",num2str(skip),".fig"),true);

fig=opts.lookup.ltplot("length","POcclude",skip,type="ratio",ratioscale="log2");
xlim([50 600])
figuresave(fig,opts,strcat("inset Sweep_Change in POcclude vs. FH1 length_skip",num2str(skip),".fig"),true);
xlim([0 600])
ylim([-11 0.5])
figuresave(fig,opts,strcat("Sweep_Change in POcclude vs. FH1 length_skip",num2str(skip),".fig"),true);

fig=opts.lookup.ltplot("CTdist","POcclude",skip,type="ratio",ratioscale="log2");
xlim([50 600])
figuresave(fig,opts,strcat("inset Sweep_Change in POcclude vs. distance to FH2_skip",num2str(skip),".fig"),true);
ylim([-11 0.5])
xlim([0 600])
figuresave(fig,opts,strcat("Sweep_Change in POcclude vs. distance to FH2_skip",num2str(skip),".fig"),true);
