% MAKE_SWEEPS generates and saves sweep figures
    % 
    % Generates and saves figures generated by the kpolysweep function and 
    % the ltplot function of the lookuptable in options.
    % Must specify an options object to be used -- this object should specify
    % where the figures will be saved as well as the appropriate lookuptable.
    %
    % See also KPOLYSWEEP, FORMIN, MAKE_EXPERIMENT_OBJS, OPTIONS, LOOKUPTABLE/LTPLOT.

%% Set variables
opts=opts;

bestfits={fit_3st,fit_4st,fit_4st_krel};

%% Make and save kpoly sweep figures
set(groot,'defaultfigureposition',[400 250 900 750]) % helps prevent cut offs in figs
for i=1:length(bestfits)
    opts.applytable(bestfits{i})
    opts.update_results_folder
    opts.resultsfolder=strcat(opts.resultsfolder," ",opts.kpoly_type,num2str(i));
    kpolysweep(opts,"PRM size","log2",true)
    kpolysweep(opts,"FH1 length","log2",true)
    kpolysweep(opts,"FH2 dist","log2",true)
    kpolysweep(opts,"NT dist","log2",true)
    kpolysweep(opts,"k_cap","log2",true)
    kpolysweep(opts,"k_del","log2",true)
    kpolysweep(opts,"r_cap","log2",true)
    if opts.kpoly_type~="3st"
        kpolysweep(opts,"r_del","log2",true)
        kpolysweep(opts,"k_rel","log2",true)
    end
end

%% Make and save polymerstat sweep figures
opts.update_results_folder
opts.resultsfolder=strcat(opts.resultsfolder," polymerstat sweep");
fig=opts.lookup.ltplot("NTdist","Prvec0",type="ratio",ratioscale="log2");
figuresave(fig,opts,"Sweep_Change in Prvec0 vs. distance to NT.fig",true);

fig=opts.lookup.ltplot("length","Prvec0",type="ratio",ratioscale="log2");
figuresave(fig,opts,"Sweep_Change in Prvec0 vs. FH1 length.fig",true);

fig=opts.lookup.ltplot("CTdist","Prvec0",type="ratio",ratioscale="log2");
figuresave(fig,opts,"Sweep_Change in Prvec0 vs. distance to FH2.fig",true);

fig=opts.lookup.ltplot("NTdist","POcclude",type="ratio",ratioscale="log2");
figuresave(fig,opts,"Sweep_Change in POcclude vs. distance to NT.fig",true);

fig=opts.lookup.ltplot("length","POcclude",type="ratio",ratioscale="log2");
figuresave(fig,opts,"Sweep_Change in POcclude vs. FH1 length.fig",true);

fig=opts.lookup.ltplot("CTdist","POcclude",type="ratio",ratioscale="log2");
figuresave(fig,opts,"Sweep_Change in POcclude vs. distance to FH2.fig",true);
